apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "node-test"
  annotations:
    "humanitec.com/orgId": "blueally-test"
    "humanitec.com/appId": "node-test"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
